management:
  security:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: validate

graphite:
  host: 172.17.0.1
  port: 2003

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  metadataMap:
    cluster: "default"
  client:
    serviceUrl:
      defaultZone: "http://localhost:9010/eureka"

hystrix:
  metrics:
    enabled: true
  stream:
    endpoint:
      enabled: true

feign:
  hystrix:
    enabled: true

---

spring:
  zipkin:
    baseUrl: "http://localhost:9030/"
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
